#!/bin/sh
cd "$(dirname "$0")/.."

status=0
report() {
    label="$1"
    shift
    hits="$("$@" 2>/dev/null)"
    if [ -n "$hits" ]; then
        count="$(printf '%s\n' "$hits" | wc -l | tr -d ' ')"
        printf '\n== %s (%s)\n%s\n' "$label" "$count" "$hits"
        status=1
    fi
}

swift_files() {
    find Corbie CorbieWidgets CorbieShare CorbieTests CorbieUITests Packages/CorbieCore/Sources Packages/CorbieCore/Tests \
        -name '*.swift' -type f ! -path '*/.build/*' -print0
}

server_files() {
    find server/supabase server/tests -type f \( -name '*.ts' -o -name '*.sql' \) ! -path '*/.temp/*' -print0
}

report "comments in swift" sh -c "$(cat <<'SH'
find Corbie CorbieWidgets CorbieShare CorbieTests CorbieUITests Packages/CorbieCore/Sources Packages/CorbieCore/Tests -name '*.swift' -type f ! -path '*/.build/*' -print0 |
    xargs -0 grep -nE '(^|[[:space:]])//|/\*' |
    grep -vE '"[^"]*//[^"]*"' |
    grep -vE 'https?://' |
    grep -vFf scripts/lint_allow.txt
SH
)"
report "comments in server code" sh -c "$(cat <<'SH'
find server/supabase server/tests -type f \( -name '*.ts' -o -name '*.sql' \) ! -path '*/.temp/*' -print0 |
    xargs -0 grep -nE '(^|[[:space:]])//|/\*|^[[:space:]]*--' |
    grep -vE '"[^"]*//[^"]*"' |
    grep -vE "'[^']*//[^']*'" |
    grep -vE 'https?://' |
    grep -vE '\*/\*|^-----|-----(BEGIN|END)'
SH
)"
report "em dash or arrow glyphs" sh -c "$(cat <<'SH'
grep -rnE '—|→|←|⇒' Corbie CorbieWidgets CorbieShare CorbieTests CorbieUITests Packages/CorbieCore/Sources Packages/CorbieCore/Tests server/supabase server/tests docs/DECISIONS.md docs/API.md README.md project.yml --include='*.swift' --include='*.ts' --include='*.sql' --include='*.md' --include='*.yml' --include='*.xcstrings'
SH
)"
report "todo, fixme, mark, step markers" sh -c "$(cat <<'SH'
grep -rnE 'TODO|FIXME|// MARK|\b[Ss]tep [0-9]|\b[Ss]tage [0-9]' Corbie CorbieWidgets CorbieShare CorbieTests CorbieUITests Packages/CorbieCore/Sources Packages/CorbieCore/Tests server/supabase server/tests --include='*.swift' --include='*.ts' --include='*.sql'
SH
)"
report "ai attribution" sh -c "$(cat <<'SH'
grep -rniE 'generated by|claude|anthropic|assistant|copilot' Corbie CorbieWidgets CorbieShare CorbieTests CorbieUITests Packages/CorbieCore/Sources Packages/CorbieCore/Tests server/supabase server/tests docs/DECISIONS.md README.md --include='*.swift' --include='*.ts' --include='*.sql' --include='*.md'
SH
)"
report "print and debugPrint in production code" sh -c "$(cat <<'SH'
find Corbie CorbieWidgets CorbieShare Packages/CorbieCore/Sources -name '*.swift' -type f -print0 | xargs -0 grep -nE '(^|[^a-zA-Z])(print|debugPrint|dump)\('
SH
)"
report "fatalError, try!, as! in production code" sh -c "$(cat <<'SH'
find Corbie CorbieWidgets CorbieShare Packages/CorbieCore/Sources -name '*.swift' -type f -print0 | xargs -0 grep -nE 'fatalError\(|try!|as! '
SH
)"
report "exclamation marks in catalog values" sh -c "$(cat <<'SH'
python3 - <<'PY'
import json
d = json.load(open('Corbie/Resources/Localizable.xcstrings'))['strings']
for key, entry in sorted(d.items()):
    for lang, loc in entry.get('localizations', {}).items():
        value = loc.get('stringUnit', {}).get('value', '')
        if '!' in value or '—' in value or '→' in value:
            print(f"{key} [{lang}]: {value}")
PY
SH
)"
report "console.log in server code" sh -c "$(cat <<'SH'
find server/supabase -name '*.ts' -type f -print0 | xargs -0 grep -nE 'console\.log\('
SH
)"

if [ "$status" -eq 0 ]; then
    echo "lint_style: ok"
fi
exit "$status"
